name: bakir_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nextflow
  - numpy
  - pandas
  - python=3.9
  - ipykernel
  - biopython
  - panel
  - pyfastx
  - yaml
  - parasail-python
  - mappy
  - dill
  - matplotlib
  - seaborn
  - clustalw
  - papermill
